version: '3.8'

services:
  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./blog-frontend:/app
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--openssl-legacy-provider
    command:
      - /bin/sh
      - -c
      - |
        npm install -g pnpm
        pnpm install
        pnpm add tslib serve -D
        pnpm build
        pnpm exec serve -s build -l 3000
    expose:
      - "3000"
    depends_on:
      - backend

  backend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./blog-backend:/app
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--openssl-legacy-provider
    command:
      - /bin/sh
      - -c
      - |
        npm install -g pnpm
        pnpm install
        pnpm add -D typescript
        pnpm exec tsc --noEmit
        pnpm run prestart:prod
        pnpm run start:prod
    expose:
      - "4000"
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db
    expose:
      - "27017"

  nginx:
    image: nginx:1.24
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  mongo-data:
