services:
  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./blog-frontend:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--openssl-legacy-provider
    command:
      - /bin/sh
      - -c
      - |
        npm install -g pnpm
        pnpm install
        pnpm build
        # Make sure this serves the frontend — change if needed
        pnpm exec serve -s build -l 3000
    depends_on:
      - backend

  backend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./blog-backend:/app
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--openssl-legacy-provider
    command:
      - /bin/sh
      - -c
      - |
        npm install -g pnpm
        pnpm install
        pnpm run prestart:prod
        pnpm run start:prod
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
